name: Upload Google Drive
on:
  push: { branches: [master] }
jobs:
  buildAndTestForSomePlatforms:
    name: Upload readme to drive
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
      # Upload to Drive
      - name: Upload to Google Drive
        uses: Jodebu/upload-to-drive@master
        with:
          target: public
          credentials: secrets.CRED
          folder: 12-ud8L-Iazpr2jk0RJ2e4ypmt_tK5cxr
