name: Main
on:
  push:
    branches:
      - 'master'

jobs:
  gdrive-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Archive files
        run: |
          sudo apt-get update
          sudo apt-get install zip
          zip -r archive.zip *

      - name: Upload to gdrive
        uses: mathisve/gdrive-upload-action@main
        with:
          filename: archive.zip
          name: test.zip
          folderId: 12-ud8L-Iazpr2jk0RJ2e4ypmt_tK5cxr
          credentials: ${{ secrets.CRED }}
